MATCH (c1:Concept)-[r1]->(c2:Concept)-[r2]->(c3:Concept) 
with c1, r1, c2, r2, c3 MATCH (c1)-[r3]->(c3) 
WHERE toInteger(r1.EDGE_YEAR) < 2012 AND toInteger(r2.EDGE_YEAR) < 2012 AND toInteger(r3.EDGE_YEAR) >= 2012
RETURN c1.NODE_HASH,c2.NODE_HASH,c3.NODE_HASH,r1.EDGE_DEDUPLICATION_HASH,r2.EDGE_DEDUPLICATION_HASH,r3.EDGE_DEDUPLICATION_HASH
order by r3.EDGE_DEDUPLICATION_HASH DESC