MATCH (c1:Concept)-[r1]->(c2:Concept)-[r2]->(c3:Concept)
with c1, r1, c2, r2, c3 MATCH (c1)-[r3]->(c3)
WHERE toInteger(r1.EDGE_YEAR) < 2012 AND toInteger(r2.EDGE_YEAR) < 2012 AND toInteger(r3.EDGE_YEAR) >= 2012 AND toInteger(r1.DOCS_SEEN)>=2 AND toInteger(r2.DOCS_SEEN)>=2 AND toInteger(r3.DOCS_SEEN)>=2 AND r1.NEGATED_COUNT = 0 AND r2.NEGATED_COUNT = 0 AND r3.NEGATED_COUNT = 0 AND c1.AVE_IDF >= 1.0 AND c2.AVE_IDF >= 1.0 AND c3.AVE_IDF >= 1.0
with c1, c2, c3, r1, r2, r3, rand() as n
RETURN c1.NODE_TEXT,c2.NODE_TEXT,c3.NODE_TEXT,r1.EDGE_LABEL,r1.EVIDENCE_TEXT,r2.EDGE_LABEL,r2.EVIDENCE_TEXT,r3.EDGE_LABEL,r3.EVIDENCE_TEXT,c1.NODE_HASH,c2.NODE_HASH,c3.NODE_HASH,r1.EDGE_DEDUPLICATION_HASH,r2.EDGE_DEDUPLICATION_HASH,r3.EDGE_DEDUPLICATION_HASH
order by n
LIMIT 20;